import javax.swing.*;
import java.awt.event.*;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import org.json.simple.*;
import org.json.simple.parser.*;

/**
 *
 * @author acer
 */
public class APPCuaca extends javax.swing.JFrame {
    private final String API_KEY = "8f5edc08790769fd6822199a89d947a9";
    private final String BASE_URL = "https://api.openweathermap.org/data/2.5/weather";
    private DefaultComboBoxModel<String> favoriteModel = new DefaultComboBoxModel<>();
    
    /**
     * Creates new form APPCuaca
     */
    public APPCuaca() {
        initComponents();
    }
    
    
    

    private void checkWeather(String city) {
        if (city.isEmpty()) {
        weatherLabel.setText("Nama kota tidak boleh kosong!");
        return;
    }

    try {
        String urlString = BASE_URL + "?q=" + city + "&appid=" + API_KEY + "&units=metric";
        URL url = new URL(urlString);
        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
        conn.setRequestMethod("GET");

        BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()));
        StringBuilder response = new StringBuilder();
        String inputLine;

        while ((inputLine = in.readLine()) != null) {
            response.append(inputLine);
        }
        in.close();

        JSONParser parser = new JSONParser();
        JSONObject jsonResponse = (JSONObject) parser.parse(response.toString());
        JSONObject main = (JSONObject) jsonResponse.get("main");
        JSONArray weatherArray = (JSONArray) jsonResponse.get("weather");
        JSONObject weather = (JSONObject) weatherArray.get(0);

        String temperature = main.get("temp").toString();
        String condition = weather.get("description").toString();

        weatherLabel.setText("<html>Cuaca: " + condition + "<br>Suhu: " + temperature + "°C</html>");
    } catch (Exception e) {
        weatherLabel.setText("<html>Gagal mengambil data cuaca!<br>Pesan error: " + e.getMessage() + "</html>");
        e.printStackTrace();
    }
}

private void addFavorite(String city) {
    if (!city.isEmpty() && !isCityInFavorites(city)) {
        favoriteModel.addElement(city);
        jComboBox1.setModel(favoriteModel); // Update combo box
    }
}

    private boolean isCityInFavorites(String city) {
        for (int i = 0; i < favoriteModel.getSize(); i++) {
            if (favoriteModel.getElementAt(i).equalsIgnoreCase(city)) {
                return true;
            }
        }
        return false;
    }
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cityField = new javax.swing.JTextField();
        checkButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        weatherLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(cityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 71, 148, -1));

        checkButton.setText("Cek Cuaca");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });
        getContentPane().add(checkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 191, -1, -1));

        jLabel1.setText("Masukkan Nama Kota");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 74, -1, -1));

        weatherLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        weatherLabel.setText("Cuaca");
        getContentPane().add(weatherLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 277, 155, 142));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 71, 157, -1));

        jButton1.setText("Tambah ke Favorit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 109, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lima-aplikasi-cuaca-ajpg-20210329071249.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        String city = cityField.getText().trim();
        checkWeather(city);
        // TODO add your handling code here:
    }//GEN-LAST:event_checkButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           String city = cityField.getText().trim();
        if (!city.isEmpty()) {
            addFavorite(city);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APPCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APPCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APPCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APPCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APPCuaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkButton;
    private javax.swing.JTextField cityField;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel weatherLabel;
    // End of variables declaration//GEN-END:variables
}
